<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Girish_PC" failures="0" tests="1" name="Default test" time="4.2" errors="0" timestamp="2024-02-18T17:56:41 EST">
  <testcase classname="com.salesforce.automationtests.LoginTest" name="ValidateLoginErrorMessage_TC4B" time="0.508"/>
  <testcase classname="com.salesforce.automationtests.LoginTest" name="ForgotPassword_TC4A" time="0.0">
    <ignored/>
  </testcase> <!-- ForgotPassword_TC4A -->
  <testcase classname="com.salesforce.automationtests.LoginTest" name="LoginToSalesForce_TC2" time="0.0">
    <ignored/>
  </testcase> <!-- LoginToSalesForce_TC2 -->
  <testcase classname="com.salesforce.automationtests.LoginTest" name="LoginErrorMessage_TC1" time="0.0">
    <ignored/>
  </testcase> <!-- LoginErrorMessage_TC1 -->
  <testcase classname="com.salesforce.automationtests.LoginTest" name="CheckRemeberMe_TC3" time="0.0">
    <ignored/>
  </testcase> <!-- CheckRemeberMe_TC3 -->
</testsuite> <!-- Default test -->
